# Page language (html attribute)
language: zh-Hans

# Main menu navigation items
menu:
  Blog: /
  Archives: /archives
  # Title: /pageName - create using `hexo new page 'pageName'`

# Post social sharing features
social:
  twitter: songouyang # set to your twitter handle

# Page sidebars
# Components will appear in the order they are specified
sidebars:
  recent: true # boolean to display 10 most recent posts
  featured: false # boolean to list all posts with tag 'featured'
  github: false # string to point to a Github profile | false to disable

# Disqus comments
disqus:
  enabled: false
  shortname: ouyangsong

# Analytics
googleAnalytics: false # false | string (UA-xxxx-x ID)

# Link to atom.xml in nav bar?
# You can use https://github.com/hexojs/hexo-generator-feed to generate these
atom: true

# Stylesheets loaded in the <head>
stylesheets:

# Scripts loaded at the end of the body
scripts: