title: 欧阳松的博客
subtitle: 'Quick Notes'
description: 'Focusing'
keywords: 博客, 程序员, 北邮, 字节跳动, @ouyangsong, @欧阳松, 北京, Python, C++, Golang, Vim
author: 欧阳松
language: zh-CN
timezone: 'Asia/Shanghai'
url: 'https://www.ouyangsong.com'
root: /
permalink: 'posts/:abbrlink/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
archive_generator:
  per_page: 15
default_category: uncategorized
category_map:
  软件技巧: software-tips
tag_map:
meta_generator: true
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: octo
deploy:
  - type: git
    repo:
      coding: git@e.coding.net:ouyangsong/ouyangsong.coding.me/ouyangsong.coding.me.git
      github: git@github.com:songouyang/songouyang.github.io.git
    branch: master
    name: songouyang
    email: songouyang@live.com
nofollow:
  enable: true
  exclude:
    - wufan.site
    - niuyuanyuanna.github.io
    - blogs.rhsphere.com
markdown:
  plugins:
    - markdown-it-footnote
